import "package:firebase_core/firebase_core.dart";
// Replace with your actual Firebase configuration generated by FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError('Add your Firebase options.');
  }
}
